### ISSUE TITLE
Fix release workflow

### ISSUE THREAD

**Issue by chris-horner** [chris-horner/SocketWeather#12]
The release GitHub workflow should run every time a PR from a branch called `release/**` is merged. I've currently listed the conditions for the workflow as
```yaml
on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

```
however it doesn't appear to work. Any advice on how to get this working in GitHub Actions would be greatly appreciated 😄
